### ISSUE TITLE
Loofah First Release Roadmap

### ISSUE THREAD

**Issue by nelind3** [LoofahMC/Loofah#1]
This is a roadmap of everything that needs doing before the first proper release of Loofah. It's sorted into the different major categories of things that need doing.
NB!: This roadmap is subject to change as more this that should be fixed are discovered!

Keyword definitions:
- "Compatible" - A given mod or plugin is considered compatible with Loofah if said mod and all test plugins work as they should when installed together. In the case of FAPI modules compatibility also requires the relevant modules own test mod be able to run and pass as expected.
- "Integration" / "Integrated" - A given mod is considered to be integrated with Loofah when Loofah has some mechanism for bringing said mod "into" the Sponge side of the game. Fx. fabric-permissions-api will be "Integrated" once there is some system that can register fabric-permissions-api as a permission service under Sponge.

# Finish the last parts of the implementation and test it
- [x] Find a fix for the super class changer issue (custom mixin extension?)

Most ever test plugin should "just work" so testing here should be prioritised so we can move onto more important work
- [ ] Test every test plugin and make sure they behave as expected
  - [ ] advancement
  - [ ] archetype
  - [ ] blockentity
  - [ ] blockstate
  - [ ] changeblock
  - [ ] channel
  - [ ] chat
  - [ ] chunk
  - [ ] chunkmanager
  - [ ] collide
  - [ ] command
  - [ ] config
  - [ ] connection
  - [ ] customdata
  - [ ] customregistry
  - [ ] damage
  - [ ] data
  - [ ] entity
  - [ ] human
  - [ ] interact
  - [ ] inventory
  - [ ] keys
  - [ ] lifecycle
  - [ ] logging
  - [ ] map
  - [ ] movement
  - [ ] notifyneighbor
  - [ ] pack
  - [ ] particle
  - [ ] portal
  - [ ] projectile
  - [ ] raytrace
  - [ ] recipe
  - [ ] resourcepack
  - [ ] scaledhealth
  - [ ] scoreboard
  - [ ] serviceloader
  - [ ] sign
  - [ ] tag
  - [ ] trades
  - [ ] validation
  - [ ] vanish
  - [ ] volumestream
  - [ ] world
  - [ ] worldborder
  - [ ] worldgen
- [ ] Test widely used community Sponge plugins
  - [ ] CommandPack
  - [ ] Luckperms
  - [ ] RegionGuard

# Fabric Mod Compatibility
Primarily/only client side modules should either already work or work with minimum modification so should be prioritised so we can get a clearer look at what actually needs doing.
- [ ] FAPI Compat (and integration where it makes sense)
  - [ ] fabric-api-base
  - [ ] fabric-api-lookup-api-v1    
  - [ ] fabric-biome-api-v1   
  - [ ] fabric-biomes-v1      
  - [ ] fabric-block-api-v1   
  - [ ] fabric-block-view-api-v2    
  - [ ] fabric-blockrenderlayer-v1  
  - [ ] fabric-client-registries    
  - [ ] fabric-client-tags-api-v1   
  - [ ] fabric-climbable-api-v1     
  - [ ] fabric-command-api-v1 
  - [ ] fabric-command-api-v2 
  - [ ] fabric-commands       
  - [ ] fabric-commands-v0    
  - [ ] fabric-containers     
  - [ ] fabric-containers-v0  
  - [ ] fabric-content-registries   
  - [ ] fabric-content-registries-v0
  - [ ] fabric-convention-tags-v1   
  - [ ] fabric-convention-tags-v2   
  - [ ] fabric-crash-report-info    
  - [ ] fabric-crash-report-info-v1 
  - [ ] fabric-data-attachment-api-v1    
  - [ ] fabric-data-generation-api-v1    
  - [ ] fabric-dimensions-v1  
  - [ ] fabric-entity-events-v1     
  - [ ] fabric-events-interaction   
  - [ ] fabric-events-interaction-v0
  - [ ] fabric-events-lifecycle     
  - [ ] fabric-events-lifecycle-v0  
  - [ ] fabric-game-rule-api-v1     
  - [ ] fabric-gametest-api-v1
  - [ ] fabric-item-api-v1    
  - [ ] fabric-item-group-api-v1    
  - [ ] fabric-item-groups    
  - [ ] fabric-item-groups-v0 
  - [ ] fabric-key-binding-api-v1   
  - [ ] fabric-keybindings    
  - [ ] fabric-keybindings-v0 
  - [ ] fabric-lifecycle-events-v1  
  - [ ] fabric-loot-api-v2    
  - [ ] fabric-loot-api-v3    
  - [ ] fabric-loot-tables-v1 
  - [ ] fabric-message-api-v1 
  - [ ] fabric-mining-level-api-v1  
  - [ ] fabric-mining-levels  
  - [ ] fabric-mining-levels-v0     
  - [ ] fabric-model-loading-api-v1 
  - [ ] fabric-models         
  - [ ] fabric-models-v0      
  - [ ] fabric-networking     
  - [ ] fabric-networking-api-v1    
  - [ ] fabric-networking-blockentity    
  - [ ] fabric-networking-blockentity-v0 
  - [ ] fabric-networking-v0  
  - [ ] fabric-object-builder-api-v1
  - [ ] fabric-object-builders
  - [ ] fabric-object-builders-v0   
  - [ ] fabric-particles-v1   
  - [ ] fabric-recipe-api-v1  
  - [ ] fabric-registry-sync  
  - [ ] fabric-registry-sync-v0     
  - [ ] fabric-renderer-api-v1
  - [ ] fabric-renderer-indigo
  - [ ] fabric-renderer-registries-v1    
  - [ ] fabric-rendering-data-attachment-v1
  - [ ] fabric-rendering-fluids-v1  
  - [ ] fabric-rendering-hooks
  - [ ] fabric-rendering-v0   
  - [ ] fabric-rendering-v1   
  - [ ] fabric-resource-conditions-api-v1
  - [ ] fabric-resource-loader
  - [ ] fabric-resource-loader-v0   
  - [ ] fabric-screen-api-v1  
  - [ ] fabric-screen-handler-api-v1
  - [ ] fabric-sound-api-v1   
  - [ ] fabric-structure-api-v1     
  - [ ] fabric-tag-extensions-v0    
  - [ ] fabric-tag-hooks      
  - [ ] fabric-textures       
  - [ ] fabric-textures-v0    
  - [ ] fabric-tool-attribute-api-v1
  - [ ] fabric-transfer-api-v1
  - [ ] fabric-transitive-access-wideners-v1
- [ ] Compatibility and Integration with community APIs
  - [ ] fabric-permissions-api
  - [ ] adventure-platform-mod
  - [ ] polymer
  - [ ] sgui
- [ ] Compatibility with widely used mods in the ecosystem
  - [ ] FabricProxy-Lite
  - [ ] Flan
  - [ ] Ledger
  - [ ] Lithium
  - [ ] Luckperms
  - [ ] StyledChat
  - [ ] StyledNicknames
  - [ ] StyledPlayerList
  - [ ] StyledSidebars
  - [ ] ViaFabric

# Misc
- [ ] Clean up the plugin loading logic to better integrate with mods
- [ ] Clean up the build script to properly `include` or relocate dependencies
- [ ] Proper naming of loggers ("Loofah/Launch" instead of "sponge" etc)

This list might not be as complete as it "should" be if you find a mod (or plugin) that's incompatible please make an issue about it.
